Controllers/DashController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoalTracker.Data;
using GoalTracker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using GoalTracker.Areas.Identity.Data;

namespace GoalTracker.Controllers
{
    [Authorize(Roles = "ConfirmedAccount")]
    public class DashController : Controller
    {
        private readonly GoalTrackerContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public DashController(GoalTrackerContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Dash
        public async Task<IActionResult> Index()
        {
            var dashes = _context.Dash.Include(t => t.Parent).Include(t => t.CreatedBy);
            return View(await dashes.ToListAsync());
        }

        // GET: Dash/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Dash == null)
            {
                return NotFound();
            }

            var dash = await _context.Dash.Where(m => m.Id == id)
                .Include(m => m.Vizualizations)
                .FirstOrDefaultAsync();
            if (dash == null)
            {
                return NotFound();
            }

            return View(dash);
        }

        // GET: Dash/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dash/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id,ParentId,Title,Description,CreatedDate,StartedDate,TargetDate,CompletedDate,Completed,Favorited,Category,Icon,Color")] Dash dash)
        {
            var user = _userManager.GetUserAsync(User).Result;

            if (user is not null)
            {
                if (ModelState.IsValid)
                {
                    dash.Id = Guid.NewGuid();
                    dash.CreatedBy = user;
                    dash.CreatedDate = DateTime.Now;
                    _context.Add(dash);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(dash);
        }

        // GET: Dash/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Dash == null)
            {
                return NotFound();
            }

            var dash = await _context.Dash.FindAsync(id);
            if (dash == null)
            {
                return NotFound();
            }
            return View(dash);
        }

        // POST: Dash/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Name,Id,ParentId,Title,Description,CreatedDate,StartedDate,TargetDate,CompletedDate,Completed,Favorited,Category,Icon,Color")] Dash dash)
        {
            if (id != dash.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dash);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DashExists(dash.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dash);
        }

        // GET: Dash/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Dash == null)
            {
                return NotFound();
            }

            var dash = await _context.Dash
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dash == null)
            {
                return NotFound();
            }

            return View(dash);
        }

        // POST: Dash/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Dash == null)
            {
                return Problem("Entity set 'GoalTrackerContext.Dash'  is null.");
            }
            var dash = await _context.Dash.FindAsync(id);
            if (dash != null)
            {
                _context.Dash.Remove(dash);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DashExists(Guid id)
        {
            return (_context.Dash?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/VizTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoalTracker.Data;
using GoalTracker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using GoalTracker.Areas.Identity.Data;

namespace GoalTracker.Controllers
{
    [Authorize(Roles = "ConfirmedAccount")]
    public class VizTypeController : Controller
    {
        private readonly GoalTrackerContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public VizTypeController(GoalTrackerContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: VizType
        public async Task<IActionResult> Index()
        {           
            var vizTypes = _context.VizType.Include(t => t.Parent).Include(t => t.CreatedBy);
            return View(await vizTypes.ToListAsync());
        }

        // GET: VizType/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.VizType == null)
            {
                return NotFound();
            }

            var vizType = await _context.VizType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vizType == null)
            {
                return NotFound();
            }

            return View(vizType);
        }

        // GET: VizType/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VizType/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ParentId,Title,Name,JSONData,Description,CreatedDate,StartedDate,TargetDate,CompletedDate,Completed,Favorited,Category,Icon,Color")] VizType vizType)
        {
            var user = _userManager.GetUserAsync(User).Result;

            if (user is not null)
            {
                if (ModelState.IsValid)
                {
                    vizType.Id = Guid.NewGuid();
                    vizType.CreatedBy = user;
                    vizType.CreatedDate = DateTime.Now;
                    _context.Add(vizType);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(vizType);
        }

        // GET: VizType/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.VizType == null)
            {
                return NotFound();
            }

            var vizType = await _context.VizType.FindAsync(id);
            if (vizType == null)
            {
                return NotFound();
            }
            return View(vizType);
        }

        // POST: VizType/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,ParentId,Title,Name,JSONData,Description,CreatedDate,StartedDate,TargetDate,CompletedDate,Completed,Favorited,Category,Icon,Color")] VizType vizType)
        {
            if (id != vizType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vizType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VizTypeExists(vizType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vizType);
        }

        // GET: VizType/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.VizType == null)
            {
                return NotFound();
            }

            var vizType = await _context.VizType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vizType == null)
            {
                return NotFound();
            }

            return View(vizType);
        }

        // POST: VizType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.VizType == null)
            {
                return Problem("Entity set 'GoalTrackerContext.VizType'  is null.");
            }
            var vizType = await _context.VizType.FindAsync(id);
            if (vizType != null)
            {
                _context.VizType.Remove(vizType);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VizTypeExists(Guid id)
        {
          return (_context.VizType?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/VizType/Create.cshtml
@model GoalTracker.Models.VizType

@{
    ViewData["Title"] = "Create";
}

<h1>Create VizType</h1>

<h4>VizType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/VizType/Delete.cshtml
@model GoalTracker.Models.VizType

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete VizType</h1>

<h3>Are you sure you want to delete this VizType?</h3>
<div>
    <h4>VizType</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/VizType/Details.cshtml
@model GoalTracker.Models.VizType

@{
    ViewData["Title"] = "Details";
}

<h1>VizType | @Model.Title</h1>

<ul class="nav">
    <li class="nav-item">
        <a class="nav-link" asp-controller="VizType" asp-action="Index">
            <i class="bi-arrow-left-square" style="font-size: 1rem; color: #0077cc;"></i>Back
        </a>
    </li>
</ul>

    <div class="row">
        <dl class="m-3 p-3">            
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
    </div>



     <div class="row justify-content-around">

        <div class="col-md-10 offset-md-1 m-3 p-3" style="min-height: 550px;">
            <canvas id="chartCanvas"></canvas>
        </div>
    </div>


@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
    @if (Model is not null)
    {
        <script src="~/js/chart_js/@(Model.Name).js" asp-append-version="true"></script>
    }

    @* <script src="~/js/chart_js/Line.js" asp-append-version="true"></script>
<script src="~/js/chart_js/Pie.js" asp-append-version="true"></script>
<script src="~/js/chart_js/Polar.js" asp-append-version="true"></script>
<script src="~/js/chart_js/Radar.js" asp-append-version="true"></script> *@
}

Views/VizType/Edit.cshtml
@model GoalTracker.Models.VizType

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit VizType</h1>

<h4>VizType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/VizType/Index.cshtml
@model IEnumerable<GoalTracker.Models.VizType>

@{
    ViewData["Title"] = "Index";
}

<h1>VizType</h1>

<ul class="nav">

    <li class="nav-item">
        <a class="nav-link" data-bs-toggle="offcanvas" href="#offCanvas_VizTypeCreate">
            <i class="bi-plus-circle" style="font-size: 1rem; color: #0077cc;"></i>Create New VizType
        </a>
        @await Html.PartialAsync("~/Views/VizType/OffCanvas/_VizTypeCreate.cshtml", new VizType() { })
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Dash" asp-action="Index">
            <i class="bi-speedometer" style="font-size: 1rem; color: #0077cc;"></i>Dashboards
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="DashViz" asp-action="Index">
            <i class="bi-graph-up" style="font-size: 1rem; color: #0077cc;"></i>DashViz
        </a>
    </li>
</ul>



<div class="col-md-10 offset-md-1">
    <div class="row g-0">

        @foreach (var vizType in Model)
        {


            <div class=" pt-3 pe-3 col-md-6">

                <div class="card" style="height: 18rem;">
                    <div class="card-header">
                        <h5 class="card-title">
                            @Html.DisplayFor(modelItem => vizType.Title) 
                            <a class="card-link align-bottom ms-auto" asp-controller="VizType" asp-action="Details"
                                asp-route-id="@vizType.Id">
                                <small>
                                    <i class="bi-graph-up" style="font-size: 1rem; color: #0077cc;"></i>View
                                </small>
                            </a>
                        </h5>
                    </div>
                    <div class="card-body">
                        <h6 class="card-subtitle mb-2 text-body-secondary">@Html.DisplayFor(modelItem => vizType.Name)</h6>

                        <p class="card-text">@vizType.Description</p>
                        <p class="card-text">@vizType.CreatedBy?.Email</p>
                        <p class="card-text">@vizType.CreatedBy?.Id</p>
                        <p class="card-text">@vizType.CreatedDate</p>

                    </div>
                    <div class="card-footer">                        

                        <a class="card-link align-bottom" data-bs-toggle="offcanvas"
                            href="#offCanvas_VizTypeDetails_@vizType.Id">
                            <i class="bi-card-text" style="font-size: 1rem; color: #0077cc;"></i>Details
                        </a>
                        @await Html.PartialAsync("~/Views/VizType/OffCanvas/_VizTypeDetails.cshtml", @vizType)



                        <a class="card-link align-bottom" data-bs-toggle="offcanvas"
                            href="#offCanvas_VizTypeEdit_@vizType.Id">
                            <i class="bi-pen" style="font-size: 1rem; color: #0077cc;"></i>Edit
                        </a>
                        @await Html.PartialAsync("~/Views/VizType/OffCanvas/_VizTypeEdit.cshtml", @vizType)


                        <a class="card-link align-bottom" data-bs-toggle="offcanvas" href="#offCanvas_VizTypeDelete_@vizType.Id">
                            <i class="bi-trash3" style="font-size: 1rem; color: #0077cc;"></i> Delete
                        </a>
                        @await Html.PartialAsync("~/Views/VizType/OffCanvas/_VizTypeDelete.cshtml", @vizType)


                    </div>
                </div>
            </div>

        }
    </div>
</div>