Models/Milestone.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GoalTracker.Models;

public class Milestone : TrackingRecord
{

    public Guid GoalId { get; set; }

    public Goal Goal { get; set; } = null!;

    public List<ActivityEntry>? Activities { get; set; }


}

Models/TrackingRecords/Milestone.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GoalTracker.Models;

public class Milestone : TrackingRecord
{

}

Controllers/MilestoneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoalTracker.Data;
using GoalTracker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using GoalTracker.Areas.Identity.Data;

namespace GoalTracker.Controllers
{
    [Authorize(Roles = "ConfirmedAccount")]
    public class MilestoneController : Controller
    {
        private readonly GoalTrackerContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public MilestoneController(GoalTrackerContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Milestone
        public async Task<IActionResult> Index()
        {
            var milestones = _context.Milestone.Include(t => t.Parent).Include(t => t.CreatedBy);
            return View(await milestones.ToListAsync());
        }

        // GET: Milestone/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Milestone == null)
            {
                return NotFound();
            }

            var milestone = await _context.Milestone
                .FirstOrDefaultAsync(m => m.Id == id);
            if (milestone == null)
            {
                return NotFound();
            }

            return View(milestone);
        }

        // GET: Milestone/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Milestone/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ParentId,Title,Description,CreatedDate,StartedDate,TargetDate,CompletedDate,Completed,Favorited,Category,Icon,Color")] Milestone milestone)
        {
            var user = _userManager.GetUserAsync(User).Result;

            if (user is not null)
            {
                if (ModelState.IsValid)
                {
                    milestone.Id = Guid.NewGuid();
                    milestone.CreatedBy = user;
                    milestone.CreatedDate = DateTime.Now;
                    _context.Add(milestone);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(milestone);
        }

        // GET: Milestone/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Milestone == null)
            {
                return NotFound();
            }

            var milestone = await _context.Milestone.FindAsync(id);
            if (milestone == null)
            {
                return NotFound();
            }
            return View(milestone);
        }

        // POST: Milestone/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,ParentId,Title,Description,CreatedDate,StartedDate,TargetDate,CompletedDate,Completed,Favorited,Category,Icon,Color")] Milestone milestone)
        {
            if (id != milestone.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(milestone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MilestoneExists(milestone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(milestone);
        }

        // GET: Milestone/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Milestone == null)
            {
                return NotFound();
            }

            var milestone = await _context.Milestone
                .FirstOrDefaultAsync(m => m.Id == id);
            if (milestone == null)
            {
                return NotFound();
            }

            return View(milestone);
        }

        // POST: Milestone/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Milestone == null)
            {
                return Problem("Entity set 'GoalTrackerContext.Milestone'  is null.");
            }
            var milestone = await _context.Milestone.FindAsync(id);
            if (milestone != null)
            {
                _context.Milestone.Remove(milestone);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MilestoneExists(Guid id)
        {
          return (_context.Milestone?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Milestone/OffCanvas/_MilestoneCreate.cshtml
@model GoalTracker.Models.Milestone

<div class="offcanvas offcanvas-end" tabindex="-1" id="offCanvas_MilestoneCreate" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h1 class="offcanvas-title" id="offcanvasRightLabel">Create Milestone</h1>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body" id="offcanvas-body">
      
        
        <form asp-controller="Milestone" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            

            <div class="form-group mb-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
           
            <div class="row">
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="CreatedDate" class="control-label"></label>
                        <input asp-for="CreatedDate" class="form-control" />
                        <span asp-validation-for="CreatedDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="TargetDate" class="control-label"></label>
                        <input asp-for="TargetDate" class="form-control" />
                        <span asp-validation-for="TargetDate" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="StartedDate" class="control-label"></label>
                        <input asp-for="StartedDate" class="form-control" />
                        <span asp-validation-for="StartedDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="CompletedDate" class="control-label"></label>
                        <input asp-for="CompletedDate" class="form-control" />
                        <span asp-validation-for="CompletedDate" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Category" class="control-label"></label>
                        <input asp-for="Category" class="form-control" />
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Status" class="control-label"></label>
                        <input asp-for="Status" class="form-control" />
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>

                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Priority" class="control-label"></label>
                        <input asp-for="Priority" class="form-control" />
                        <span asp-validation-for="Priority" class="text-danger"></span>
                    </div>
                </div>
            </div>


            <div class="form-group mb-3">
                <label asp-for="Links" class="control-label"></label>
                <input asp-for="Links" class="form-control" />
                <span asp-validation-for="Links" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="FileAttachments" class="control-label"></label>
                <input asp-for="FileAttachments" class="form-control" />
                <span asp-validation-for="FileAttachments" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Assignee" class="control-label"></label>
                        <input asp-for="Assignee" class="form-control" />
                        <span asp-validation-for="Assignee" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Reviewer" class="control-label"></label>
                        <input asp-for="Reviewer" class="form-control" />
                        <span asp-validation-for="Reviewer" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <div class="form-group mb-3">
                        <label asp-for="Color" class="control-label">Color Picker</label>
                        <input asp-for="Color" type="color" class="form-control form-control-color"
                            id="goalColorInputCreate" value="#563d7c" title="Choose your color">
                        <span asp-validation-for="Color" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-9">
                    <div class="form-group mb-3">
                        <label asp-for="ColorSuggestions" class="control-label"></label>
                        <div class="row">
                            @if (@Model!.ColorSuggestions != null)
                            {
                                @foreach (var c in @Model!.ColorSuggestions)
                                {
                                    <input asp-for="ColorSuggestions" type="color"
                                        class="form-control form-control-color d-inline mx-3 colorSuggestion"
                                        id="DashColorSuggestion_@c.Value" value="@c.Value" data-value="@c.Value"
                                        data-targetId="goalColorInputCreate" title="Suggestion">
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group form-check mb-3">
                        <label class="form-check-label">
                            @Html.DisplayNameFor(model => model.Completed)
                            <input class="form-check-input" asp-for="Completed" />
                        </label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group form-check mb-3">
                        <label class="form-check-label">
                            @Html.DisplayNameFor(model => model.Favorited)
                            <input class="form-check-input" asp-for="Favorited" />
                        </label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Icon" class="control-label"></label>
                        <input asp-for="Icon" class="form-control" />
                        <span asp-validation-for="Icon" class="text-danger"></span>
                    </div>
                </div>
            </div>

                
            <div class="form-group mb-3 float-end">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>

        @section Scripts {
            @{
                await Html.RenderPartialAsync("_ValidationScriptsPartial");
            }
        }

    </div>
</div>

Views/Milestone/OffCanvas/_MilestoneDelete.cshtml
@model GoalTracker.Models.Milestone

<div class="offcanvas offcanvas-end" tabindex="-1" id="offCanvas_MilestoneDelete_@Model.Id"
    aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h1 class="offcanvas-title" id="offcanvasRightLabel">Delete Milestone</h1>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body" id="offcanvas-body">

        <div class="alert alert-danger d-flex align-items-center py-0" role="alert">
            <i class="bi-exclamation-triangle-fill" style="font-size: 1rem; color: #dc3545;"></i>
            Are you sure you want to delete this Milestone?
        </div>

               <dl>

            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ParentId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ParentId)
            </dd>



            <div class="row">
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CreatedDate)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.TargetDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TargetDate)
                    </dd>

                </div>
            </div>


            <div class="row">
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.StartedDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.StartedDate)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.CompletedDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CompletedDate)
                    </dd>
                </div>
            </div>






            <div class="row">
                <div class="col">

                    <dt>
                        @Html.DisplayNameFor(model => model.Category)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Category)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.Priority)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Priority)
                    </dd>

                </div>
            </div>




            <dt>
                @Html.DisplayNameFor(model => model.Links)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Links)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.FileAttachments)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.FileAttachments)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tags)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tags)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Notes)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Notes)
            </dd>






            <div class="row">
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.Assignee)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Assignee)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.Reviewer)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Reviewer)
                    </dd>
                </div>
            </div>










            <dt>
                @Html.DisplayNameFor(model => model.Color)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Color)
            </dd>




            <div class="row">
                <div class="col">

                    <dt>
                        @Html.DisplayNameFor(model => model.Completed)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Completed)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.Favorited)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Favorited)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.Icon)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Icon)
                    </dd>
                </div>
            </div>




        </dl>


        <div class="form-group mb-3 float-end">
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-outline-danger" />
            </form>
        </div>



    </div>
</div>

Views/Milestone/OffCanvas/_MilestoneEdit.cshtml
@model GoalTracker.Models.Milestone

<div class="offcanvas offcanvas-end" tabindex="-1" id="offCanvas_MilestoneEdit_@Model.Id" aria-labelledby="offcanvasRightLabel">
            <div class="offcanvas-header">
                <h1 class="offcanvas-title" id="offcanvasRightLabel">Edit Milestone</h1>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body" id="offcanvas-body">
            
                        
                        <form asp-controller="Milestone" asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <input type="hidden" asp-for="CreatedDate" />
                            <div class="form-group mb-3">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>


            <div class="form-group mb-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="CreatedDate" class="control-label"></label>
                        <input asp-for="CreatedDate" class="form-control" />
                        <span asp-validation-for="CreatedDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="TargetDate" class="control-label"></label>
                        <input asp-for="TargetDate" class="form-control" />
                        <span asp-validation-for="TargetDate" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="StartedDate" class="control-label"></label>
                        <input asp-for="StartedDate" class="form-control" />
                        <span asp-validation-for="StartedDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="CompletedDate" class="control-label"></label>
                        <input asp-for="CompletedDate" class="form-control" />
                        <span asp-validation-for="CompletedDate" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Category" class="control-label"></label>
                        <input asp-for="Category" class="form-control" />
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Status" class="control-label"></label>
                        <input asp-for="Status" class="form-control" />
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>

                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Priority" class="control-label"></label>
                        <input asp-for="Priority" class="form-control" />
                        <span asp-validation-for="Priority" class="text-danger"></span>
                    </div>
                </div>
            </div>


            <div class="form-group mb-3">
                <label asp-for="Links" class="control-label"></label>
                <input asp-for="Links" class="form-control" />
                <span asp-validation-for="Links" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="FileAttachments" class="control-label"></label>
                <input asp-for="FileAttachments" class="form-control" />
                <span asp-validation-for="FileAttachments" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Assignee" class="control-label"></label>
                        <input asp-for="Assignee" class="form-control" />
                        <span asp-validation-for="Assignee" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Reviewer" class="control-label"></label>
                        <input asp-for="Reviewer" class="form-control" />
                        <span asp-validation-for="Reviewer" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <div class="form-group mb-3">
                        <label asp-for="Color" class="control-label">Color Picker</label>
                        <input asp-for="Color" type="color" class="form-control form-control-color"
                            id="goalColorInputCreate" value="#563d7c" title="Choose your color">
                        <span asp-validation-for="Color" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-9">
                    <div class="form-group mb-3">
                        <label asp-for="ColorSuggestions" class="control-label"></label>
                        <div class="row">
                            @if (@Model!.ColorSuggestions != null)
                            {
                                @foreach (var c in @Model!.ColorSuggestions)
                                {
                                    <input asp-for="ColorSuggestions" type="color"
                                        class="form-control form-control-color d-inline mx-3 colorSuggestion"
                                        id="DashColorSuggestion_@c.Value" value="@c.Value" data-value="@c.Value"
                                        data-targetId="goalColorInputCreate" title="Suggestion">
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group form-check mb-3">
                        <label class="form-check-label">
                            @Html.DisplayNameFor(model => model.Completed)
                            <input class="form-check-input" asp-for="Completed" />
                        </label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group form-check mb-3">
                        <label class="form-check-label">
                            @Html.DisplayNameFor(model => model.Favorited)
                            <input class="form-check-input" asp-for="Favorited" />
                        </label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="Icon" class="control-label"></label>
                        <input asp-for="Icon" class="form-control" />
                        <span asp-validation-for="Icon" class="text-danger"></span>
                    </div>
                </div>
            </div>

                            <div class="form-group mb-3 float-end">
                                <input type="submit" value="Save" class="btn btn-outline-primary" />
                            </div>
                        </form>
              

              
            @section Scripts {
                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
            }



            </div>
        </div>