Models/Link.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Policy;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using GoalTracker.Areas.Identity.Data;

namespace GoalTracker.Models;

public class Link
{
    public Guid Id {get;set;}

    public string? Title {get;set;}

    public string? Url {get;set;}

    public ApplicationUser? CreatedBy { get; set; }

    [Display(Name = "Created")]
    [DataType(DataType.Date)]
    public DateTime CreatedDate { get; set; }
    
}

Models/TrackingRecords/Link.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Policy;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using GoalTracker.Areas.Identity.Data;

namespace GoalTracker.Models;

public class Link : TrackingRecord
{
    [Display(Name = "Display Name")]
    public string? DisplayName {get;set;}

    public string? Url {get;set;}
    
}

Controllers/LinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoalTracker.Data;
using GoalTracker.Models;
using Microsoft.AspNetCore.Authorization;

namespace GoalTracker.Controllers
{
    [Authorize(Roles = "ConfirmedAccount")]
    public class LinkController : Controller
    {
        private readonly GoalTrackerContext _context;

        public LinkController(GoalTrackerContext context)
        {
            _context = context;
        }

        // GET: Link
        public async Task<IActionResult> Index()
        {
              return _context.Link != null ? 
                          View(await _context.Link.ToListAsync()) :
                          Problem("Entity set 'GoalTrackerContext.Link'  is null.");
        }

        // GET: Link/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Link == null)
            {
                return NotFound();
            }

            var link = await _context.Link
                .FirstOrDefaultAsync(m => m.Id == id);
            if (link == null)
            {
                return NotFound();
            }

            return View(link);
        }

        // GET: Link/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Link/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DisplayName,Url,Id,ParentId,Title,Description,CreatedDate,StartedDate,TargetDate,CompletedDate,Completed,Favorited,Category,Icon,Color")] Link link)
        {
            if (ModelState.IsValid)
            {
                link.Id = Guid.NewGuid();
                _context.Add(link);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(link);
        }

        // GET: Link/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Link == null)
            {
                return NotFound();
            }

            var link = await _context.Link.FindAsync(id);
            if (link == null)
            {
                return NotFound();
            }
            return View(link);
        }

        // POST: Link/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("DisplayName,Url,Id,ParentId,Title,Description,CreatedDate,StartedDate,TargetDate,CompletedDate,Completed,Favorited,Category,Icon,Color")] Link link)
        {
            if (id != link.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(link);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LinkExists(link.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(link);
        }

        // GET: Link/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Link == null)
            {
                return NotFound();
            }

            var link = await _context.Link
                .FirstOrDefaultAsync(m => m.Id == id);
            if (link == null)
            {
                return NotFound();
            }

            return View(link);
        }

        // POST: Link/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Link == null)
            {
                return Problem("Entity set 'GoalTrackerContext.Link'  is null.");
            }
            var link = await _context.Link.FindAsync(id);
            if (link != null)
            {
                _context.Link.Remove(link);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LinkExists(Guid id)
        {
          return (_context.Link?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Link/OffCanvas/_LinkCreate.cshtml
@model GoalTracker.Models.Link

<div class="offcanvas offcanvas-end" tabindex="-1" id="offCanvas_LinkCreate" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h1 class="offcanvas-title" id="offcanvasRightLabel">Create Link</h1>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body" id="offcanvas-body">
      
        
        <form asp-controller="Link" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="CreatedDate" class="control-label"></label>
                        <input asp-for="CreatedDate" class="form-control" />
                        <span asp-validation-for="CreatedDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="TargetDate" class="control-label"></label>
                        <input asp-for="TargetDate" class="form-control" />
                        <span asp-validation-for="TargetDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mb-3">
                        <label asp-for="CompletedDate" class="control-label"></label>
                        <input asp-for="CompletedDate" class="form-control" />
                        <span asp-validation-for="CompletedDate" class="text-danger"></span>
                    </div>
                </div>
            </div>     
            <div class="form-group mb-3">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Icon" class="control-label"></label>
                <input asp-for="Icon" class="form-control" />
                <span asp-validation-for="Icon" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-3">
                    <div class="form-group mb-3">
                        <label asp-for="Color" class="control-label">Color Picker</label>
                        <input asp-for="Color" type="color" class="form-control form-control-color" 
                            id="goalColorInputCreate" value="#563d7c" title="Choose your color">
                        <span asp-validation-for="Color" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-9">
                    <div class="form-group mb-3">
                        <label asp-for="ColorSuggestions" class="control-label"></label>
                        <div class="row">
                            @if (@Model!.ColorSuggestions != null) 
                            {
                                @foreach (var c in @Model!.ColorSuggestions) 
                                {                                            
                                    <input asp-for="ColorSuggestions" type="color" class="form-control form-control-color d-inline mx-3 colorSuggestion" 
                                        id="LinkColorSuggestion_@c.Value" value="@c.Value" data-value="@c.Value" data-targetId="goalColorInputCreate" title="Suggestion">                                                   
                                } 
                            }                    
                        </div>    
                    </div>       
                </div>
            </div> 

            <div class="form-group form-check mb-3">
                <label class="form-check-label">
                    @Html.DisplayNameFor(model => model.Completed)
                    <input class="form-check-input" asp-for="Completed" />
                </label>
            </div>
                
            <div class="form-group mb-3 float-end">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>

        @section Scripts {
            @{
                await Html.RenderPartialAsync("_ValidationScriptsPartial");
            }
        }

    </div>
</div>

Views/Link/OffCanvas/_LinkDelete.cshtml
@model GoalTracker.Models.Link

<div class="offcanvas offcanvas-end" tabindex="-1" id="offCanvas_LinkDelete_@Model.Id"
    aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h1 class="offcanvas-title" id="offcanvasRightLabel">Delete Link</h1>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body" id="offcanvas-body">

        <div class="alert alert-danger d-flex align-items-center py-0" role="alert">
            <i class="bi-exclamation-triangle-fill" style="font-size: 1rem; color: #dc3545;"></i>
            Are you sure you want to delete this Link?
        </div>

        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <div class="row">
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CreatedDate)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.TargetDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TargetDate)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.CompletedDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CompletedDate)
                    </dd>
                </div>
            </div>




            <dt>
                @Html.DisplayNameFor(model => model.Completed)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Completed)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Category)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Category)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Icon)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Icon)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Color)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Color)
            </dd>
        </dl>


        <div class="form-group mb-3 float-end">
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-outline-danger" />
            </form>
        </div>



    </div>
</div>

Views/Link/OffCanvas/_LinkDetails.cshtml
@model GoalTracker.Models.Link

<div class="offcanvas offcanvas-end" tabindex="-1" id="offCanvas_LinkDetails_@Model.Id" aria-labelledby="offcanvasRightLabel">
            <div class="offcanvas-header">
                <h1 class="offcanvas-title" id="offcanvasRightLabel">Link Details</h1>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body" id="offcanvas-body">
             
             
        
        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <div class="row">
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CreatedDate)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.TargetDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TargetDate)
                    </dd>
                </div>
                <div class="col">
                    <dt>
                        @Html.DisplayNameFor(model => model.CompletedDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CompletedDate)
                    </dd>
                </div>
            </div>




            <dt>
                @Html.DisplayNameFor(model => model.Completed)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Completed)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Category)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Category)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Icon)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Icon)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Color)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Color)
            </dd>
        </dl>


    </div>
</div>

Views/Link/OffCanvas/_LinkEdit.cshtml
@model GoalTracker.Models.Link

<div class="offcanvas offcanvas-end" tabindex="-1" id="offCanvas_LinkEdit_@Model.Id" aria-labelledby="offcanvasRightLabel">
            <div class="offcanvas-header">
                <h1 class="offcanvas-title" id="offcanvasRightLabel">Edit Link</h1>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body" id="offcanvas-body">
            
                        
                        <form asp-controller="Link" asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <input type="hidden" asp-for="CreatedDate" />
                            <div class="form-group mb-3">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="form-group mb-3">
                                        <label asp-for="CreatedDate" class="control-label"></label>
                                        <input asp-for="CreatedDate" class="form-control" />
                                        <span asp-validation-for="CreatedDate" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group mb-3">
                                        <label asp-for="TargetDate" class="control-label"></label>
                                        <input asp-for="TargetDate" class="form-control" />
                                        <span asp-validation-for="TargetDate" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group mb-3">
                                        <label asp-for="CompletedDate" class="control-label"></label>
                                        <input asp-for="CompletedDate" class="form-control" />
                                        <span asp-validation-for="CompletedDate" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>       
                            <div class="form-group mb-3">
                                <label asp-for="Category" class="control-label"></label>
                                <input asp-for="Category" class="form-control" />
                                <span asp-validation-for="Category" class="text-danger"></span>
                            </div>
                            <div class="form-group mb-3">
                                <label asp-for="Icon" class="control-label"></label>
                                <input asp-for="Icon" class="form-control" />
                                <span asp-validation-for="Icon" class="text-danger"></span>
                            </div>
                        <div class="row">
                            <div class="col-3">
                                <div class="form-group mb-3">
                                    <label asp-for="Color" class="control-label">Color Picker</label>
                                    <input asp-for="Color" type="color" class="form-control form-control-color" 
                                        id="goalColorInputEdit_@Model.Id" value="@Model.Color" title="Choose your color">
                                    <span asp-validation-for="Color" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-9">
                                <div class="form-group mb-3">
                                    <label asp-for="ColorSuggestions" class="control-label"></label>
                                    <div class="row">
                                        @if (@Model!.ColorSuggestions != null) 
                                        {
                                            @foreach (var c in @Model!.ColorSuggestions) 
                                            {                                            
                                                <input asp-for="ColorSuggestions" type="color" class="form-control form-control-color d-inline mx-3 colorSuggestion" 
                                                    id="LinkColorSuggestion_@c.Value" value="@c.Value" data-value="@c.Value" data-targetId="goalColorInputEdit_@Model.Id" title="Suggestion">                                                   
                                            } 
                                        }                    
                                    </div>    
                                </div>     
                            </div>
                        </div>

                            <div class="form-group form-check mb-3">
                                <label class="form-check-label">
                                    @Html.DisplayNameFor(model => model.Completed)
                                    <input class="form-check-input" asp-for="Completed" />                    
                                </label>
                            </div>
                            <div class="form-group mb-3 float-end">
                                <input type="submit" value="Save" class="btn btn-outline-primary" />
                            </div>
                        </form>
              

              
            @section Scripts {
                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
            }



            </div>
        </div>